// src/utils/itemIndexing.ts
//
// The single answer to "is /objetos/{slug}/ indexable?", shared by the item
// page (robots meta) and the sitemap, so a page can never be `noindex` while
// listed in the sitemap or the other way round.
//
// The answer comes from src/data/itemSeoManifest.json, generated by
// scripts/item-seo-manifest.ts with getItemSeoPolicy() over the whole PokeAPI
// catalog (family-level evidence and duplicate names need every item, which a
// request cannot afford). Items absent from the manifest are indexable.

import manifest from '../data/itemSeoManifest.json';

const NOINDEX = manifest.noindex as Record<string, string>;

export const ITEM_NOINDEX_ROBOTS = 'noindex,follow';

/** Why this item is noindex, or null when it is indexable. */
export function itemNoindexReason(slug: string): string | null {
  return Object.prototype.hasOwnProperty.call(NOINDEX, slug) ? NOINDEX[slug] : null;
}

export function isItemIndexable(slug: string): boolean {
  return itemNoindexReason(slug) === null;
}

/** `<meta name="robots">` value for an item page; undefined = default (indexable). */
export function itemRobots(slug: string): string | undefined {
  return isItemIndexable(slug) ? undefined : ITEM_NOINDEX_ROBOTS;
}

/** Sitemap filter: only indexable items. */
export function indexableItems<T extends { name: string }>(items: T[]): T[] {
  return items.filter((item) => isItemIndexable(item.name));
}
