#!/usr/bin/env tsx
// scripts/item-seo-manifest.ts
//
// Regenerates src/data/itemSeoManifest.json: the slugs the sitemap leaves out
// and the item pages mark `noindex,follow`, computed from live PokeAPI data by
// the same policy the pages use (src/utils/itemSeo.ts).
//
// Why a committed snapshot: the policy needs each item's detail (description,
// sprite, attributes, relations) and the duplicate-name check needs the whole
// catalog, i.e. ~2200 requests — fine for a script, not for the sitemap route.
//
//   npm run data:items-seo            -> rewrite the manifest
//   npm run data:items-seo -- --check -> exit 1 if the committed manifest is stale
//
// Re-run when PokeAPI fills in data (e.g. the Legends Z-A mega stones): an
// item leaves the manifest as soon as it has enough real data.

import { readFile, writeFile } from 'node:fs/promises';
import { getAllItems } from '../src/services/pokeapi';
import { classifyItemFamily, findDuplicateNameVariants, getItemSeoPolicy, itemQualityScore, summarizeFamilies, type ItemSeoInput } from '../src/utils/itemSeo';

const OUT = new URL('../src/data/itemSeoManifest.json', import.meta.url);
const CONCURRENCY = 12;

async function fetchItem(url: string): Promise<ItemSeoInput & { url: string }> {
  for (let attempt = 0; attempt < 4; attempt++) {
    try {
      const res = await fetch(url);
      if (res.ok) return { ...(await res.json()), url };
    } catch {
      /* retry */
    }
  }
  throw new Error(`could not fetch ${url}`);
}

async function main() {
  const catalog = await getAllItems();
  const details: ItemSeoInput[] = new Array(catalog.length);
  let next = 0;
  await Promise.all(
    Array.from({ length: CONCURRENCY }, async () => {
      while (next < catalog.length) {
        const i = next++;
        details[i] = await fetchItem(catalog[i].url);
      }
    })
  );

  const variants = findDuplicateNameVariants(details.map((d) => ({ name: d.name, names: d.names, quality: itemQualityScore(d) })));
  const families = summarizeFamilies(details);
  const noindex: Record<string, string> = {};
  const byFamily: Record<string, { total: number; noindex: number }> = {};

  for (const item of details) {
    const family = classifyItemFamily(item.name, item.category?.name);
    const policy = getItemSeoPolicy(item, families.get(family));
    byFamily[family] ??= { total: 0, noindex: 0 };
    byFamily[family].total++;
    let reason: string | null = policy.decision === 'noindex' ? `family-without-content: ${policy.reason}` : null;
    if (!reason && variants.has(item.name)) reason = `duplicate-name-variant of ${variants.get(item.name)}`;
    if (reason) {
      noindex[item.name] = reason;
      byFamily[family].noindex++;
    }
  }

  const manifest = {
    _note: 'Generated by scripts/item-seo-manifest.ts from PokeAPI. Slugs listed here are noindex,follow and excluded from the sitemap.',
    pokeapiItemCount: catalog.length,
    noindexCount: Object.keys(noindex).length,
    noindex: Object.fromEntries(Object.entries(noindex).sort(([a], [b]) => a.localeCompare(b))),
  };
  const json = JSON.stringify(manifest, null, 1) + '\n';

  if (process.argv.includes('--check')) {
    const current = await readFile(OUT, 'utf8');
    const stale = JSON.stringify(JSON.parse(current).noindex) !== JSON.stringify(manifest.noindex);
    console.log(stale ? 'STALE: itemSeoManifest.json differs from live PokeAPI data' : 'itemSeoManifest.json is up to date');
    process.exit(stale ? 1 : 0);
  }
  await writeFile(OUT, json);
  console.log(`items ${catalog.length}, noindex ${manifest.noindexCount}, indexable ${catalog.length - manifest.noindexCount}`);
  console.table(byFamily);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
